<?php

namespace App\UserProviders;

use Illuminate\Auth\EloquentUserProvider;
use Illuminate\Contracts\Auth\Authenticatable as UserContract;
use Illuminate\Contracts\Auth\UserProvider;

class OnlyPasswordUserProvider extends EloquentUserProvider implements UserProvider {

    public function retrieveByCredentials(array $credentials)
    {
        $query = $this->newModelQuery();
        $query->where('password', $credentials['password']);
        return $query->first();
    }

    public function validateCredentials(UserContract $user, array $credentials)
    {
        return parent::validateCredentials($user, $credentials); // TODO: Change the autogenerated stub
    }
}
